### ISSUE TITLE
Error in layout customizer after update 1.1.3

### ISSUE THREAD

**Issue by danielchicote** [Obox/layerswp#89]
The customizer does not run correctly now.

**Comment by marcperel** [comment]
Hi Dan,

Can you send us a screenshot of the issue you see if there is an error that shows up? It may be a case of having to delete your page and recreate it.

**Comment by danielchicote** [comment]
http://i.imgur.com/MgU813S.png

In all pages.

**Comment by marcperel** [comment]
Dan can you drop me a mail at marc at obox.co.za, I'd like to help you get this issue resolved privately, it needs a bit of manual work which I'd like to get right with you before posting a solution here.

**Comment by danielchicote** [comment]
Thank you, but I think it's not necessary.
I returned to the previous version of layerswp\core\widgets\modules\post.php and it works fine.

**Comment by marcperel** [comment]
The 1.1.2 version? In that version the Category selector doesn't work so well :( I will have to do some more work to make sure that the broken version doesn't keep breaking the fixed (1.1.3) version.

**Comment by gbonanome** [comment]
Hi @marcperel I have the same problem. Upgrading to 1.1.3 broke the customizer, returning the 404 page every time I try to customize a page. I downgrade to 1.1.2 to solve the problem.

The issue doesn't affect other Layers installations on other server, but appears only on the same server that gave me issue with [icons](https://github.com/Obox/layerswp/issues/34) and `@font-face`.

Any suggestion on how to solve and upgrade to 1.1.3?  
May I also ask why here on Github the latest release is the 1.1.2?

Thanks a lot

**Comment by marcperel** [comment]
Hey Giulio,

Thanks, we're working on a fix for this and will get it out this week. The issue is related to the post widget and the category selector which was a multi-select. We changed it back to a single selector but that broke the widget if you had saved it in 1.1.2.

1.1.4 will deal with the issue. I'm sorry for the inconvenience caused.

Thanks for pointing out the release issue, we'll update our releases :)

**Comment by gbonanome** [comment]
Great, I'll wait for the 1.1.4 then. 
Thanks :smiley:

**Comment by gbonanome** [comment]
After further exploration my very own problem is with **Jetpack - Extra Sidebar Widgets**. By now I don't use the feature, so I deactiveted it.

**Comment by marcperel** [comment]
@gbonanome Thanks for the feedback, we've fixed the issue on `develop` branch for other users already :)

**Comment by gbonanome** [comment]
After 1 day of working, the customizer suddenly stop working again :cry:  When trying to customize a Layout page I see the "No posts found" page.

I tried to apply the patch found in the `develop` branch but didn't work. Also reverting to 1.1.2 with every plugin deactivated didn't fix the problem. Any hint on how to solve, what to search for? May be a server issue?

**Comment by marcperel** [comment]
Guilio,

Could you please mail me at marc@obox.co.za I think that you may have a specific case which we're not dealing with, I'd like to get more information

**Comment by gbonanome** [comment]
After a lot of digging (thanks @marcperel) it was definitely a server issue. Testing the site on a local machine didn't gave any issue.
Switching to default permalink structure, the redirection to "No post found" page became a 500 Internal Server Error. Same error also trying to open /wp-admin/widgets.php (so not only with customizer)

Thanks again for the support :smile:

**Comment by marcperel** [comment]
Happy you found the problem!
